//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsole.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class employees : DbContext
    {
        public employees()
            : base("name=employees")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<per_cal_type> per_cal_type { get; set; }
        public DbSet<per_degree> per_degree { get; set; }
        public DbSet<per_dept> per_dept { get; set; }
        public DbSet<per_floor> per_floor { get; set; }
        public DbSet<per_group> per_group { get; set; }
        public DbSet<per_leave> per_leave { get; set; }
        public DbSet<per_nation> per_nation { get; set; }
        public DbSet<per_penalty> per_penalty { get; set; }
        public DbSet<per_penalty_code> per_penalty_code { get; set; }
        public DbSet<per_penalty_type> per_penalty_type { get; set; }
        public DbSet<per_room> per_room { get; set; }
        public DbSet<per_sex> per_sex { get; set; }
        public DbSet<per_shoe> per_shoe { get; set; }
        public DbSet<per_state> per_state { get; set; }
        public DbSet<per_title> per_title { get; set; }
        public DbSet<per_worker_type> per_worker_type { get; set; }
        public DbSet<employee> employee { get; set; }
    }
}
