//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsole.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string cWorker_no { get; set; }
        public string cName { get; set; }
        public Nullable<System.DateTime> dbirthday { get; set; }
        public string cCard_ID { get; set; }
        public byte iWorker_type { get; set; }
        public byte iSex { get; set; }
        public string cNation_code { get; set; }
        public string cDegree_code { get; set; }
        public bool lMarried { get; set; }
        public string cWorker_Id { get; set; }
        public string cState_code { get; set; }
        public string cFather_name { get; set; }
        public string cMather_name { get; set; }
        public string cHome_tel { get; set; }
        public string cHome_address { get; set; }
        public string cVoucher { get; set; }
        public Nullable<System.DateTime> dHire_date { get; set; }
        public string cDept_code { get; set; }
        public int iTitle_ID { get; set; }
        public byte iSal_type { get; set; }
        public byte iCal_type { get; set; }
        public decimal nSalary { get; set; }
        public Nullable<decimal> nAllowance { get; set; }
        public Nullable<System.DateTime> dCurr_sal_date { get; set; }
        public string cAccount { get; set; }
        public int iFloor_ID { get; set; }
        public int iGroup_ID { get; set; }
        public string cShoe_code { get; set; }
        public Nullable<System.DateTime> dOut_date { get; set; }
        public string cOut_reason { get; set; }
        public bool lNo_to_bank { get; set; }
        public string cNo_to_bank_reason { get; set; }
        public bool lSafety_flag { get; set; }
        public string cSafety_no { get; set; }
        public bool lCity_flag { get; set; }
        public Nullable<bool> lNew_subsidy { get; set; }
        public string remarks { get; set; }
        public string cStop_meal { get; set; }
        public string cScan_loc { get; set; }
        public Nullable<System.DateTime> dAmend_date { get; set; }
        public string cAmend_user { get; set; }
        public string cUser_id { get; set; }
        public bool lSub_hot_flag { get; set; }
        public string cbox_code { get; set; }
        public Nullable<System.DateTime> dperiod_of_validity_date { get; set; }
        public Nullable<System.DateTime> dchg_title_date { get; set; }
        public byte[] msrepl_tran_version { get; set; }
        public Nullable<decimal> nhot_subsidy { get; set; }
        public string cSupervisor_No { get; set; }
        public string cEngName { get; set; }
        public decimal nOther_Subsidy { get; set; }
        public string cOther_Subsidy_Remark { get; set; }
    }
}
