//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsole.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_shoe
    {
        public string cShoe_code { get; set; }
        public string cShoe_no { get; set; }
        public byte[] msrepl_tran_version { get; set; }
    }
}
