//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsole.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_penalty_code
    {
        public string cPenalty_code { get; set; }
        public string cPenalty_desc { get; set; }
        public byte iPenalty_type { get; set; }
        public Nullable<bool> lcount_flag { get; set; }
        public Nullable<System.DateTime> dAmend_date { get; set; }
        public string cAmend_user { get; set; }
    }
}
