//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsole.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_group
    {
        public int iGroup_ID { get; set; }
        public string cgroup_desc { get; set; }
        public string cDept_code { get; set; }
        public string cStart_am { get; set; }
        public string cEnd_am { get; set; }
        public string cStart_noon { get; set; }
        public string cEnd_noon { get; set; }
        public string cStart_pm { get; set; }
        public string cEnd_pm { get; set; }
        public string cStart_tip { get; set; }
        public Nullable<System.DateTime> dAmend_date { get; set; }
        public string cAmend_user { get; set; }
        public byte[] msrepl_tran_version { get; set; }
    }
}
